### ISSUE TITLE
Stickiness based on context

### ISSUE THREAD

**Issue by jackcb123** [Nasdaq/active_record_proxy_adapters#4]
Hi! Thanks for building this! We have a db that is writing every second of every day. It looks to me like 'last_write_at' is a global variable for the whole db. Is that true? So for us, it would never hit the replica.

Are you are intending to eventually make this more contextual like the way https://github.com/instacart/makara works? Our desired behavior is that, even if there is some other write occurring on the db somewhere, within the connection it will use the replica until there is a write (and then of course stick for 2 or 5 seconds what have you). This is how we're doing things with makara right now, but they don't work for Rails 8.

**Comment by mateuscruz** [comment]
Hello @jackcb123. `last_write_at` is not a global variable for the whole db. It is currently an instance variable for each proxy and each instance of the adapter has its own unique proxy instance. The way Rails already works is each thread will get exactly one adapter from connection pool, so that should be enough for the vast majority of use cases in a regular Rails application (including an HTTP request) so, unless your workflow does something else other than the regular 
Rails workflow, it should be enough for you.

Although we have not implemented the same strategy as makara using a Rack middleware, the outcome should be the exact same: each requests has its own context.

We have plans to add a context API that would allow the creation of a custom context of your choice (as noted [here](https://github.com/Nasdaq/active_record_proxy_adapters/blob/main/lib/active_record_proxy_adapters/primary_replica_proxy.rb#L163)).

I hope that answers your question.

**Comment by mateuscruz** [comment]
@jackcb123  I have updated README to describe how it works a little bit better.  Closing this out for now. Happy holidays!

https://github.com/Nasdaq/active_record_proxy_adapters?tab=readme-ov-file#stickiness-context
